# Generated by Django 3.2.7 on 2021-09-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0006_auto_20210924_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='users_image/default_user_pic.png', null=True, upload_to='users_image'),
        ),
    ]
